name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Install native build dependencies
        run: |
          sudo apt update
          sudo apt install \
            build-essential \
            meson \
            ninja-build \
            nasm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.22.1'

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Check Library Stats
        run: |
          ls -lh library/build/intermediates/merged_native_libs/debug/*/out/lib/*/*
          readelf -d library/build/intermediates/merged_native_libs/debug/*/out/lib/*/*

      # Archive the generated AAR file
      - name: Archive AAR
        uses: actions/upload-artifact@v4
        with:
          path: library/build/outputs/aar/*.aar

